spring:
  application:
    name: shopping-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
      fail-fast: true